name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - id: cache-date
        run: echo "week=$(date --utc '+%V')" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: .cache
          key: zensical-${{ steps.cache-date.outputs.week }}
          restore-keys: |
            zensical-
      - run: pip install zensical
      - run: zensical build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
